{
 "title": "Wikimedia events",
 "time": { "from": "2026-06-11T17:17:37.584Z", "to": "2026-06-11T17:34:00.577Z" },
 "panels": [
  {
   "title": "Minor Edit Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"minor_edit_count\") / sum(\"edit_count\") * 100 \nFROM \"edit_stats_1m\" \nWHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT sum(\"edit_count\") \nFROM \"edit_stats_1m\" \nWHERE $timeFilter \nGROUP BY time(1m), \"wiki\""
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "SELECT sum(\"bot_edit_count\"), sum(\"edit_count\") - sum(\"bot_edit_count\") \nFROM \"edit_stats_1m\" \nWHERE $timeFilter \nGROUP BY time(1m)"
    }
   ]
  },
  {
   "title": "Live Raw Edits Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"title\", \"wiki\", \"user\", \"length_delta\", \"bot\" \nFROM \"page_edits\" \nWHERE $timeFilter \nORDER BY time DESC \nLIMIT 50"
    }
   ]
  },
  {
   "title": "Average Length Delta",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"avg_length_delta\") \nFROM \"edit_stats_1m\" \nWHERE $timeFilter"
    }
   ]
  }
 ]
}