a1.sources= wikimedia
a1.channels= channel
a1.sinks=kafka

# Configure the Exec Source for continuous live streaming
a1.sources.wikimedia.type    = exec
a1.sources.wikimedia.command = curl -sN https://stream.wikimedia.org/v2/stream/recentchange
a1.sources.wikimedia.restart = true
a1.sources.wikimedia.restartThrottle = 5000
a1.sources.wikimedia.batchSize = 100
a1.sources.wikimedia.channels = channel


a1.channels.channel.type = memory
a1.channels.channel.capacity = 10000
a1.channels.channel.transactionCapacity = 100

a1.sinks.kafka.channel = channel
a1.sinks.kafka.type = org.apache.flume.sink.kafka.KafkaSink
a1.sinks.kafka.kafka.bootstrap.servers = localhost:9092
a1.sinks.kafka.kafka.topic = wikimedia
a1.sinks.kafka.flumeBatchSize = 20
a1.sinks.kafka.allowTopicOverride = false
